#pragma once

/// FLAG1
#define ENCRYPTED_TYPE_NETCARD				0x01
#define ENCRYPTED_TYPE_VERSION				0x02
#define ENCRYPTED_TYPE_COMPUTERNAME			0x04
#define ENCRYPTED_TYPE_MEMORY				0x08
#define ENCRYPTED_TYPE_OSANDBITS			0x10
#define ENCRYPTED_TYPE_MOTHERBOARD			0x20
#define ENCRYPTED_TYPE_ALLINFO				0xFFFFFFFF

/// FLAG2
#define ENCRYPTED_CODE_NORMAL				0x01